# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cheked',
            field=models.BooleanField(default=False),
        ),
    ]
